import { ReactChildren } from '../typings';
import Head from 'next/head';
import Footer from './Footer';
import Nav from './Nav';

const Layout = ({ children }: ReactChildren) => {
  return (
    <>
      <Head>
        <title>NEHOPCOSA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main>{children}</main>
      <Footer />
    </>
  );
};

export default Layout;
